#!/bin/tcsh -f
#$ -cwd
#$ -o sys_2_car_int2_diox_opt_sto3g_gga.job.o$JOB_ID
#$ -q all.q
#$ -j y
#$ -N q-sys_2_car_int2_diox_opt_sto3g_gga
#$ -pe shared 12


setenv QC /usr/software/qchem_511
source /usr/software/qchem_511/MGCF_qcenv.csh

cd $SGE_O_WORKDIR
/bin/hostname

set echo
awk '{ print $1 }' $PE_HOSTFILE > sys_2_car_int2_diox_opt_sto3g_gga.nodes
setenv QCMACHINEFILE sys_2_car_int2_diox_opt_sto3g_gga.nodes
setenv QCSCRATCH $SGE_O_WORKDIR/$JOB_ID
/bin/mkdir -p $QCSCRATCH
setenv QCLOCALSCR /scr/$USER/$JOB_ID
/bin/mkdir -p $QCLOCALSCR
/usr/bin/env

/usr/software/qchem_511/bin/qchem -nt 12 sys_2_car_int2_diox_opt_sto3g_gga.in sys_2_car_int2_diox_opt_sto3g_gga.out

